/* GitHub 一键保存：附件与 content.json 在同一次原子提交中发布；版本冲突不覆盖。 */
"use strict";
let archiveConnected=false,archiveToken="";
const ARCHIVE_CONNECTION=CONFIG+":session";
function archiveRepositoryAPI(c){return "https://api.github.com/repos/"+encodeURIComponent(c.owner)+"/"+encodeURIComponent(c.repo);}
function archiveApiHeaders(){const token=archiveToken||$("token").value.trim();return {...headers(),...(token?{Authorization:"Bearer "+token}:{}),"Content-Type":"application/json"};}
async function archiveGitAPI(c,path,method="GET",payload){const r=await fetch(archiveRepositoryAPI(c)+path,{method,headers:archiveApiHeaders(),...(payload?{body:JSON.stringify(payload)}:{}),cache:"no-store"});if(!r.ok){let details="";try{details=(await r.json()).message||"";}catch{}throw Error(`GitHub 操作失败（${r.status}）：${details||"检查令牌权限、分支和网络。"}`);}return r.json();}
function archiveAssetReferences(x){const references=[];x.pages.forEach(p=>walk(p.blocks,b=>{if(b.src)references.push({ref:b,name:b.assetName||blockTitle(b),type:b.type,id:b.assetId});}));x.works.forEach(w=>w.stages.forEach(s=>s.files.forEach(f=>references.push({ref:f,name:f.name,type:f.type,id:f.assetId||f.id}))));x.instruments.forEach(i=>i.sessions.forEach(s=>(s.files||[]).forEach(f=>references.push({ref:f,name:f.name,type:f.type,id:f.assetId||f.id}))));return references;}
remote=async function(c){const api=archiveRepositoryAPI(c)+"/contents/content.json?ref="+encodeURIComponent(c.branch);const r=await fetch(api,{headers:archiveApiHeaders(),cache:"no-store"});if(r.status===404)return {sha:null,data:null};if(!r.ok)throw Error("GitHub 内容读取失败（"+r.status+"）。");const file=await r.json();let text;if(file.content){const bytes=Uint8Array.from(atob(file.content.replace(/\s/g,"")),ch=>ch.charCodeAt(0));text=new TextDecoder().decode(bytes);}else{const raw=await fetch(api,{headers:{...archiveApiHeaders(),Accept:"application/vnd.github.raw+json"},cache:"no-store"});if(!raw.ok)throw Error("无法读取较大的 content.json。");text=await raw.text();}return {sha:file.sha,data:validate(JSON.parse(text))};};
function archiveOpenSync(){for(const k of ["owner","repo","branch"])$(k).value=settings[k]||(k==="owner"?"gonghuiyun0610":k==="repo"?"music-notebook":"main");$("token").value=archiveToken;$("syncStatus").textContent=archiveConnected?"已连接。可读取远端，或保存本机全部修改。":"先连接并验证一次，以后点击顶部按钮直接保存。";$("sync").showModal();}
function archiveUpdateCloud(){const b=$("cloud");b.textContent=archiveConnected?"保存到 GitHub":"连接 GitHub";}
async function archiveConnect(){if(busy)return;busy=true;const control=$("archive-connect");control.disabled=true;try{const c=getConfig();archiveToken=$("token").value.trim();if(!archiveToken)throw Error("请填写授权令牌。");const repo=await archiveGitAPI(c,"");if(!repo.permissions?.push)throw Error("这个令牌没有该仓库的内容写入权限。");await archiveGitAPI(c,"/git/ref/heads/"+encodeURIComponent(c.branch));const latest=await remote(c);if(!Object.hasOwn(bases,key(c)))bases[key(c)]=latest.sha;archiveConnected=true;cache();archiveUpdateCloud();if($("archive-remember").checked)sessionStorage.setItem(ARCHIVE_CONNECTION,JSON.stringify({token:archiveToken,config:c}));else sessionStorage.removeItem(ARCHIVE_CONNECTION);$("syncStatus").textContent=latest.sha?"已连接。保存会用当前本机内容更新仓库；如需先接着另一台设备的内容，请点读取 GitHub 内容。":"已连接，第一次保存将创建 content.json。";status("GitHub 已连接，编辑后可一键保存。");}catch(e){archiveConnected=false;archiveUpdateCloud();$("syncStatus").textContent=e.message;}finally{busy=false;control.disabled=false;}}
async function archiveSaveGitHub(){if(busy)return;if(!archiveConnected||!archiveToken){archiveOpenSync();return;}if(Archive.timer)return archiveNotice("请先暂停并结束当前练习，再保存到 GitHub，确保练习记录完整。");const c=settings,snapshot=clone(validate(data));busy=true;$("cloud").disabled=true;$("push").disabled=true;$("pull").disabled=true;document.querySelector("main").inert=true;document.querySelector("aside").inert=true;try{
    const branchRef=await archiveGitAPI(c,"/git/ref/heads/"+encodeURIComponent(c.branch));const parent=branchRef.object.sha;const latest=await remote(c);if(!Object.hasOwn(bases,key(c))||bases[key(c)]!==latest.sha)throw Error("另一台设备已更新内容。请先导出本机备份，再读取最新内容并整理；本次不会覆盖。");
    const commit=await archiveGitAPI(c,"/git/commits/"+parent);const tree=[];const seen=new Map();const refs=archiveAssetReferences(snapshot);for(const item of refs){if(!item.ref.src.startsWith("asset:"))continue;const id=item.ref.src.slice(6);if(seen.has(id)){item.ref.src=seen.get(id);continue;}const blob=await dbGet(id);if(!blob)throw Error("本地附件缺失："+item.name);if(blob.size>50*1024*1024)throw Error("附件超过50 MB："+item.name);const ext=(item.name||blob.name||"").match(/\.[a-z0-9]{1,8}$/i)?.[0]||".bin";const path="assets/"+id+ext;status("正在保存附件："+item.name);$("syncStatus").textContent="正在保存附件："+item.name;const encoded=(await blobDataURL(blob)).split(",")[1];const uploaded=await archiveGitAPI(c,"/git/blobs","POST",{content:encoded,encoding:"base64"});tree.push({path,mode:"100644",type:"blob",sha:uploaded.sha});const src="./"+path;seen.set(id,src);item.ref.src=src;}
    delete snapshot.assets;const raw=JSON.stringify(validate(snapshot),null,2);if(new TextEncoder().encode(raw).length>10*1024*1024)throw Error("内容索引超过10 MB，请减少内嵌数据或拆分档案。");const contentBlob=await archiveGitAPI(c,"/git/blobs","POST",{content:raw,encoding:"utf-8"});tree.push({path:"content.json",mode:"100644",type:"blob",sha:contentBlob.sha});const createdTree=await archiveGitAPI(c,"/git/trees","POST",{base_tree:commit.tree.sha,tree});const createdCommit=await archiveGitAPI(c,"/git/commits","POST",{message:"Save music archive "+new Date().toISOString(),tree:createdTree.sha,parents:[parent]});await archiveGitAPI(c,"/git/refs/heads/"+encodeURIComponent(c.branch),"PATCH",{sha:createdCommit.sha,force:false});
    data=validate(snapshot);bases[key(c)]=contentBlob.sha;dirty=false;let localSaved=true;try{await dbPut(STORE,clone({data,bases,dirty}));}catch{localSaved=false;}cache();render();status("已保存到 GitHub ✓ · "+new Date().toLocaleTimeString("zh-CN")+(localSaved?"":" · 本机存储失败，请导出备份"));$("syncStatus").textContent="全部内容和附件已保存。GitHub Pages 部署完成后，公开页面会更新。";
  }catch(e){status("保存失败："+e.message+" 本机修改保留。");$("syncStatus").textContent=e.message;if(!$("sync").open)archiveOpenSync();$("syncStatus").textContent=e.message;}finally{busy=false;$("cloud").disabled=false;$("push").disabled=false;$("pull").disabled=false;document.querySelector("main").inert=false;document.querySelector("aside").inert=false;}}
$("cloud").onclick=()=>archiveConnected?archiveSaveGitHub():archiveOpenSync();$("push").onclick=async()=>{if(!archiveConnected)await archiveConnect();if(archiveConnected)await archiveSaveGitHub();};
$("pull").onclick=async()=>{if(busy)return;if(Archive.timer)return archiveNotice("先结束当前练习再读取远端。");try{if(!archiveConnected){await archiveConnect();if(!archiveConnected)return;}const r=await remote(settings);if(!r.data)throw Error("仓库还没有 content.json，可以先保存本机内容。");archiveConfirm("读取 GitHub 内容？","将替换当前本机档案。若有未同步修改，请先导出完整备份。",async()=>{stop();data=r.data;bases[key(settings)]=r.sha;dirty=false;current=data.pages[0]?.id||null;Archive.view="home";await dbPut(STORE,clone({data,bases,dirty}));cache();$("sync").close();render();status("已读取 GitHub 最新内容。");});}catch(e){$("syncStatus").textContent=e.message;}};
// 令牌只保存在内存或用户选择的当前标签页会话；永不进入导出文件及仓库。
const sync=$("sync");const tokenLabel=$("token").closest("label");tokenLabel.firstChild.textContent="授权令牌";const remember=archiveCheck("刷新后保持连接（仅当前标签页）",true);remember.input.id="archive-remember";const disconnect=button("断开连接",()=>{archiveToken="";$("token").value="";archiveConnected=false;sessionStorage.removeItem(ARCHIVE_CONNECTION);archiveUpdateCloud();$("syncStatus").textContent="连接已清除。";});sync.insertBefore(remember.node,$("syncStatus"));const connect=button("连接并验证",archiveConnect,"primary");connect.id="archive-connect";sync.querySelector(".actions").prepend(connect,disconnect);const syncDescription=sync.querySelector("p");syncDescription.textContent="连接后，一键保存全部课程、练习、乐器日志、作品和附件。公开仓库及公开网站中的资料可被他人读取。";sync.querySelector("p.muted").firstChild.textContent="只授权这个仓库，Contents 设为 Read and write。令牌不会写入备份或代码。 ";
try{const saved=JSON.parse(sessionStorage.getItem(ARCHIVE_CONNECTION)||"null");if(saved?.token&&saved.config){archiveToken=saved.token;settings=saved.config;archiveConnected=true;$("token").value=archiveToken;}}catch{}archiveUpdateCloud();
function archiveDownloadFile(name,blob){const url=URL.createObjectURL(blob);el("a",{href:url,download:name}).click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
download=async function(){try{if(Archive.timer)archiveTimerSave();const backup=clone(validate(data));backup.assets={};const references=archiveAssetReferences(backup);const ids=[...new Set(references.map(x=>x.ref.src.startsWith("asset:")?x.ref.src.slice(6):x.id).filter(Boolean))];for(const id of ids){let blob=await dbGet(id);if(!blob){const entry=references.find(x=>x.id===id);if(!entry||entry.ref.src.startsWith("asset:"))throw Error("附件缺失，先在原设备同步或重新添加。");const response=await fetch(entry.ref.src,{cache:"no-store"});if(!response.ok)throw Error("无法备份附件："+entry.name);blob=await response.blob();if(blob.size>50*1024*1024)throw Error("备份附件超过50 MB。");blob=new File([blob],entry.name,{type:blob.type||entry.ref.type||"application/octet-stream"});}backup.assets[id]={name:blob.name||"attachment",data:await blobDataURL(blob)};references.filter(x=>x.id===id||x.ref.src==="asset:"+id).forEach(x=>x.ref.src="asset:"+id);}archiveDownloadFile("Music_Archive_Backup_"+archiveDate()+".json",new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}));status("已导出完整备份，包含本机附件。");}catch(e){status("备份失败："+e.message);}};$("export").onclick=download;
$("importFile").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(Archive.timer)throw Error("先结束当前练习再导入。");if(file.size>300*1024*1024)throw Error("完整备份最大300 MB。");const raw=JSON.parse(await file.text()),next=validate(raw);if(!confirm("导入会替换本机档案，请先导出当前备份。继续？"))return;for(const [id,asset]of Object.entries(raw.assets||{})){if(!/^[a-zA-Z0-9-]+$/.test(id)||typeof asset.data!=="string"||!/^data:[a-z0-9.+-]+\/[a-z0-9.+-]+;base64,/i.test(asset.data))throw Error("备份附件无效。");const r=await fetch(asset.data),blob=await r.blob();if(blob.size>50*1024*1024)throw Error("备份单个附件超过50 MB。");await dbPut(id,new File([blob],asset.name||"attachment",{type:blob.type}));}delete next.assets;data=next;current=data.pages[0]?.id||null;Archive.view="home";changed();render();status("已导入完整备份。");}catch(err){status("导入失败："+err.message);}finally{e.target.value="";}};
