/* 无外部依赖的 3D 知识关系图：Canvas 透视投影、拖动旋转、缩放、点选。 */
"use strict";
function archiveGraphModel(){const entries=archiveEntries();const ids=new Set(entries.map(x=>x.b.id));const edges=data.relations.filter(r=>ids.has(r.from)&&ids.has(r.to)&&r.from!==r.to).map(r=>({...r}));const pages=new Map();entries.forEach(x=>{const previous=pages.get(x.p.id);if(previous)edges.push({from:previous,to:x.b.id,type:"sameLesson"});pages.set(x.p.id,x.b.id);});return {entries,edges};}
function archiveGraphPositions(entries,edges){
  const hash=s=>{let n=2166136261;for(const c of s)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0;};const courses=[...new Set(entries.map(x=>x.p.courseId))];
  const points=entries.map(x=>{const group=courses.indexOf(x.p.courseId),angle=group*2*Math.PI/Math.max(1,courses.length),h=hash(x.b.id),a=(h%1000)/1000*2*Math.PI;return {id:x.b.id,x:Math.cos(angle)*120+Math.cos(a)*65,y:((h>>>10)%1000)/1000*180-90,z:Math.sin(angle)*120+Math.sin(a)*65,anchorX:Math.cos(angle)*120,anchorZ:Math.sin(angle)*120};});
  const byId=new Map(points.map(p=>[p.id,p]));if(points.length<=300){for(let step=0;step<90;step++){for(const p of points){p.x+=(p.anchorX-p.x)*.008;p.z+=(p.anchorZ-p.z)*.008;}for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){const a=points[i],b=points[j];let dx=a.x-b.x,dy=a.y-b.y,dz=a.z-b.z,dist=Math.sqrt(dx*dx+dy*dy+dz*dz)||1;const force=Math.min(1.8,200/(dist*dist));a.x+=dx/dist*force;a.y+=dy/dist*force;a.z+=dz/dist*force;b.x-=dx/dist*force;b.y-=dy/dist*force;b.z-=dz/dist*force;}for(const r of edges){const a=byId.get(r.from),b=byId.get(r.to);if(!a||!b)continue;const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,dist=Math.hypot(dx,dy,dz)||1,force=(dist-78)*.012;a.x+=dx/dist*force;a.y+=dy/dist*force;a.z+=dz/dist*force;b.x-=dx/dist*force;b.y-=dy/dist*force;b.z-=dz/dist*force;}}}return points;
}
function archiveRenderGraph(root){const model=archiveGraphModel();const count=model.entries.filter(x=>x.b.practiceTags.length).length;const panel=el("section",{class:"archive-panel"});const head=el("div",{class:"archive-section-head"},[el("h2",{text:"知识关系图"}),el("span",{class:"muted",text:`分类整理 ${count} / ${model.entries.length} · ${model.entries.length?Math.round(count/model.entries.length*100):0}%`})]);panel.append(head,el("div",{class:"archive-graph-legend"},[el("span",{class:"graph-dot graph-classified",text:"● 已分类"}),el("span",{class:"graph-dot",text:"● 未分类"}),el("span",{text:"实线：已确认关联 · 虚线：同课内容"})]));if(!model.entries.length){panel.append(el("p",{class:"muted",text:"把知识点加入练习库，就会出现在这里。未分类也能练习和加入计划。"}));root.append(panel);return;}
  const viewport=el("div",{class:"archive-graph-viewport"});const canvas=el("canvas",{"aria-label":"3D知识图，拖动旋转；也可从下方选择节点",role:"img"});viewport.append(canvas);panel.append(viewport);
  const picker=archiveSelect([["","选择知识节点"],...model.entries.map(x=>[x.b.id,blockTitle(x.b)])],"");const controls=el("div",{class:"archive-actions"},[picker,button("＋ 放大",()=>{zoom=Math.min(2.4,zoom*1.15);draw();}),button("－ 缩小",()=>{zoom=Math.max(.35,zoom/1.15);draw();}),button("正面视角",()=>{angleY=0;angleX=.12;zoom=1;draw();})]);panel.append(controls,el("p",{class:"muted",text:"拖动旋转 · 滚轮缩放 · 点击节点查看连接；位置按课程和关联组织，颜色只表示分类进度。"}));const detail=el("div",{class:"archive-graph-detail"});panel.append(detail);root.append(panel);
  const g=canvas.getContext("2d");if(!g){detail.textContent="当前浏览器无法显示图形，可使用分类卡片查看全部知识。";return;}
  let angleY=0,angleX=.12,zoom=1,selected=null,projected=[],drag=null,width=600,height=460;const points=archiveGraphPositions(model.entries,model.edges);const nodeById=new Map(model.entries.map(x=>[x.b.id,x]));
  function choose(id){selected=id;picker.value=id||"";detail.replaceChildren();if(id){const x=nodeById.get(id);const stats=archiveSessionStats(id);const relations=model.edges.filter(r=>r.from===id||r.to===id);detail.append(el("h3",{text:blockTitle(x.b)}),el("p",{class:"muted",text:archivePath(x.p)}),el("p",{text:(x.b.practiceTags.length?"已分类："+x.b.practiceTags.join("、"):"未分类 · 可正常调用")+` · ${stats.count}次 · ${archiveMinutes(stats.seconds)}`}));relations.forEach(r=>{const other=nodeById.get(r.from===id?r.to:r.from);if(other)detail.append(el("p",{class:"muted",text:blockTitle(other.b)+" · "+(r.type==="sameLesson"?"同课内容":r.type==="related"?"相互关联":r.from===id?"当前知识是其前置基础":"当前知识的前置基础")}));});detail.append(el("div",{class:"archive-actions"},[button("打开知识",()=>locate(x.p,x.b)),button("分类",()=>archiveClassify(x.b)),button("关联 / 重点",()=>archiveRelationDialog(id)),button("开始练习",()=>archiveStartPractice(id),"primary")]));}draw();}
  function draw(){const ratio=Math.min(window.devicePixelRatio||1,2);width=viewport.clientWidth||600;height=viewport.clientHeight||460;canvas.width=width*ratio;canvas.height=height*ratio;canvas.style.width=width+"px";canvas.style.height=height+"px";g.setTransform(ratio,0,0,ratio,0,0);g.clearRect(0,0,width,height);const scale=Math.min(width/520,height/390)*zoom;
    projected=points.map(p=>{const x=p.x*Math.cos(angleY)+p.z*Math.sin(angleY),z=-p.x*Math.sin(angleY)+p.z*Math.cos(angleY),y=p.y*Math.cos(angleX)-z*Math.sin(angleX),depth=p.y*Math.sin(angleX)+z*Math.cos(angleX),perspective=500/(500+depth);return {id:p.id,x:width/2+x*scale*perspective,y:height/2+y*scale*perspective,z:depth,size:Math.max(5,9*perspective*scale)};});const byId=new Map(projected.map(p=>[p.id,p]));const adjacent=new Set(model.edges.filter(r=>r.from===selected||r.to===selected).flatMap(r=>[r.from,r.to]));
    for(const r of model.edges){const a=byId.get(r.from),b=byId.get(r.to);if(!a||!b)continue;const active=selected&&(r.from===selected||r.to===selected);g.globalAlpha=selected&&!active?.2:r.type==="sameLesson"?.4:.65;g.strokeStyle=active?"#34776b":"#9caec0";g.lineWidth=active?2:1;g.setLineDash(r.type==="sameLesson"?[3,4]:[]);g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.stroke();if(r.type==="prerequisite"){const dx=b.x-a.x,dy=b.y-a.y,angle=Math.atan2(dy,dx),endX=b.x-Math.cos(angle)*(b.size+4),endY=b.y-Math.sin(angle)*(b.size+4);g.beginPath();g.moveTo(endX-7*Math.cos(angle-.4),endY-7*Math.sin(angle-.4));g.lineTo(endX,endY);g.lineTo(endX-7*Math.cos(angle+.4),endY-7*Math.sin(angle+.4));g.stroke();}}
    g.setLineDash([]);projected.sort((a,b)=>b.z-a.z).forEach(p=>{const b=nodeById.get(p.id).b;g.globalAlpha=selected&&p.id!==selected&&!adjacent.has(p.id)?.28:1;g.fillStyle=b.practiceTags.length?"#5b8bc8":"#95a1b0";g.beginPath();g.arc(p.x,p.y,p.size,0,2*Math.PI);g.fill();if(p.id===selected){g.strokeStyle="#34776b";g.lineWidth=2;g.beginPath();g.arc(p.x,p.y,p.size+5,0,2*Math.PI);g.stroke();}if(model.entries.length<=28||p.id===selected||adjacent.has(p.id)){const label=blockTitle(b),text=label.length>13?label.slice(0,12)+"…":label;g.font="12px system-ui";g.textAlign="center";const tw=g.measureText(text).width,tx=Math.max(tw/2+5,Math.min(width-tw/2-5,p.x)),ty=Math.max(14,Math.min(height-8,p.y+p.size+18));g.fillStyle="#faf9f5";g.fillRect(tx-tw/2-3,ty-12,tw+6,16);g.fillStyle="#243d39";g.fillText(text,tx,ty);const stats=archiveSessionStats(p.id);if(stats.count){g.fillStyle="#243d39";g.fillText(({stuck:"?",again:"↻",fluent:"✓"})[b.proficiency||"again"],p.x+p.size+8,p.y);}}});g.globalAlpha=1;
  }
  picker.onchange=()=>choose(picker.value||null);canvas.style.touchAction="none";canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,moved:false};canvas.setPointerCapture?.(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>2)drag.moved=true;angleY+=dx*.009;angleX=Math.max(-1.4,Math.min(1.4,angleX+dy*.009));drag.x=e.clientX;drag.y=e.clientY;draw();};canvas.onpointerup=e=>{if(drag&&!drag.moved){const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;const nearest=[...projected].sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];choose(nearest&&Math.hypot(nearest.x-x,nearest.y-y)<Math.max(22,nearest.size+9)?nearest.id:null);}drag=null;};canvas.onpointercancel=()=>drag=null;canvas.addEventListener("wheel",e=>{e.preventDefault();zoom=Math.max(.35,Math.min(2.4,zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});const observer=new ResizeObserver(draw);observer.observe(viewport);draw();Archive.graphDispose=()=>observer.disconnect();
}
