/* 独立 MIDI 模块：4/4、十六分网格，兼容原有文字/鼓模块与 JSON 保存。 */
'use strict';
function midiDefaults(){return {name:'我的 MIDI 织体',bpm:90,bars:1,octave:3,length:4,velocity:90,notes:[]};}
function midiValidate(b){if(typeof b.name!=='string'||!Number.isFinite(b.bpm)||b.bpm<40||b.bpm>220||![1,2,4].includes(b.bars)||!Number.isInteger(b.octave)||b.octave<2||b.octave>5||![1,2,4,8,16].includes(b.length)||!Number.isInteger(b.velocity)||b.velocity<1||b.velocity>127||!Array.isArray(b.notes)||b.notes.length>2048)throw Error('MIDI 模块参数不正确。');for(const n of b.notes){if(!Number.isInteger(n.pitch)||n.pitch<36||n.pitch>96||!Number.isInteger(n.start)||n.start<0||!Number.isInteger(n.duration)||n.duration<1||n.start+n.duration>b.bars*16||!Number.isInteger(n.velocity)||n.velocity<1||n.velocity>127)throw Error('MIDI 音符参数不正确。');}for(let i=0;i<b.notes.length;i++)for(let j=i+1;j<b.notes.length;j++){const a=b.notes[i],c=b.notes[j];if(a.pitch===c.pitch&&a.start<c.start+c.duration&&c.start<a.start+a.duration)throw Error('同音高的 MIDI 音符不能重叠。');}}
function midiPitch(p){return ['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][p%12]+(Math.floor(p/12)-1);}
function midiToggle(b,pitch,step){const old=b.notes.find(n=>n.pitch===pitch&&step>=n.start&&step<n.start+n.duration);if(old){b.notes.splice(b.notes.indexOf(old),1);return;}const duration=Math.min(b.length,b.bars*16-step);if(b.notes.some(n=>n.pitch===pitch&&step<n.start+n.duration&&n.start<step+duration))return; b.notes.push({pitch,start:step,duration,velocity:b.velocity});}
function midiRender(card,b){const heading=editing?el('input',{value:b.name,'aria-label':'MIDI 名称',oninput:e=>{b.name=e.target.value;changed();}}):el('h2',{text:b.name});card.append(el('div',{class:'block-head'},[heading,el('span',{class:'pill',text:'MIDI · '+b.bars+' 小节'})]));const selected=el('div',{class:'midi-selected',text:'点格子添加音符；点已有音符删除。'});function refresh(){stop();changed();render();}
const play=el('button',{class:'primary',text:'▶ 播放','data-play':b.id,onclick:async()=>{if(transport?.id===b.id){stop();return;}try{await midiStart(b);play.textContent='■ 停止';}catch{status('音频启动失败，请使用支持 Web Audio 的浏览器。');}}});const bpm=el('input',{type:'number',min:40,max:220,value:b.bpm,'aria-label':'MIDI BPM',onchange:e=>{b.bpm=Math.min(220,Math.max(40,Number(e.target.value)||90));e.target.value=b.bpm;changed();}});const controls=el('div',{class:'controls'},[play,el('label',{text:'BPM '},[bpm]),el('button',{text:'导出 .mid',onclick:()=>midiDownload(b)})]);card.append(controls);
function select(value,options,label,onchange){const s=el('select',{'aria-label':label,onchange});for(const [v,text] of options){const o=el('option',{value:v,text});if(Number(v)===value)o.setAttribute('selected','');s.append(o);}return el('label',{text:label+' '},[s]);}
if(editing){let editExisting=false;const editMode=el('button',{text:'模式：添加 / 删除',onclick:()=>{editExisting=!editExisting;editMode.textContent=editExisting?'模式：修改已有音符':'模式：添加 / 删除';card.dataset.editNotes=String(editExisting);}});const bar=select(b.bars,[[1,'1 小节'],[2,'2 小节'],[4,'4 小节']],'长度',e=>{const next=Number(e.target.value);if(b.notes.some(n=>n.start+n.duration>next*16)&&!confirm('缩短小节会删除超出部分，并截短跨越结尾的音符。继续？')){e.target.value=b.bars;return;}b.bars=next;b.notes=b.notes.filter(n=>n.start<next*16).map(n=>({...n,duration:Math.min(n.duration,next*16-n.start)}));refresh();});const octave=select(b.octave,[[2,'C2–C4'],[3,'C3–C5'],[4,'C4–C6'],[5,'C5–C7']],'显示音域',e=>{b.octave=Number(e.target.value);refresh();});const length=select(b.length,[[1,'十六分'],[2,'八分'],[4,'四分'],[8,'二分'],[16,'全音符']],'新音符时值',e=>{b.length=Number(e.target.value);changed();});const velocity=el('input',{type:'number',min:1,max:127,value:b.velocity,'aria-label':'新音符力度',onchange:e=>{b.velocity=Math.min(127,Math.max(1,Math.round(Number(e.target.value)||90)));e.target.value=b.velocity;changed();}});card.append(el('div',{class:'midi-options'},[editMode,bar,octave,length,el('label',{text:'新音符力度 '},[velocity]),el('button',{text:'C 大调分解和弦示例',onclick:()=>{if(b.notes.length&&!confirm('用示例替换这个模块的全部音符？'))return;const root=(b.octave+1)*12;b.notes=[];for(let n=0;n<b.bars*16;n+=2)b.notes.push({pitch:root+[0,4,7,12][(n/2)%4],start:n,duration:2,velocity:b.velocity});refresh();}}),el('button',{text:'清空音符',onclick:()=>{if(confirm('清空这个 MIDI 块的音符？')){b.notes=[];refresh();}}})]));card.append(selected);}
const steps=b.bars*16,grid=el('div',{class:'piano-grid',style:'grid-template-columns:64px repeat('+steps+', 28px)'});grid.append(el('span',{class:'piano-key',text:'音高'}));for(let s=0;s<steps;s++)grid.append(el('span',{class:'count',text:s%4===0?String(Math.floor(s/16)+1)+'.'+String((s%16)/4+1):['','e','&','a'][s%4],'data-rhythm':b.id,'data-step':s}));const low=(b.octave+1)*12;for(let pitch=low+24;pitch>=low;pitch--){const black=[1,3,6,8,10].includes(pitch%12);grid.append(el('span',{class:'piano-key'+(black?' black':'')+(pitch%12===0?' root':''),text:midiPitch(pitch)}));for(let s=0;s<steps;s++){const note=b.notes.find(n=>n.pitch===pitch&&s>=n.start&&s<n.start+n.duration);const button=el('button',{class:'piano-cell'+(black?' black':'')+(s%4===0?' beat':'')+(note?' note':'')+(note?.start===s?' onset':''),'data-rhythm':b.id,'data-step':s,'aria-label':midiPitch(pitch)+' 第'+(s+1)+'格'+(note?' 已有音符':''),'aria-pressed':String(!!note),title:note?midiPitch(pitch)+' · 时值 '+note.duration+' 格 · 力度 '+note.velocity:midiPitch(pitch),onclick:()=>{if(!editing){status('点击「编辑页面」后可添加或删除音符。');return;}if(card.dataset.editNotes==='true'){if(note)midiEditNote(b,note);else status('请点击已有音符，或切回添加模式。');return;}stop();midiToggle(b,pitch,s);changed();render();}});grid.append(button);}}
card.append(el('div',{class:'piano-scroll'},[grid]));const hidden=b.notes.filter(n=>n.pitch<low||n.pitch>low+24).length;card.append(el('div',{class:'hint',text:'共 '+b.notes.length+' 个音符'+(hidden?' · '+hidden+' 个在当前显示音域之外':'')+'。每格为十六分音符；同一列的不同音高可组成和弦。试听为合成键盘音色。'}));}
function midiSound(n,time,duration,bus){const gain=ctx.createGain();gain.connect(bus);gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(n.velocity/127*.12,time+.008);gain.gain.exponentialRampToValueAtTime(Math.max(.001,n.velocity/127*.035),time+Math.max(.015,duration*.75));gain.gain.linearRampToValueAtTime(0,time+duration+.035);const o=ctx.createOscillator();o.type='triangle';o.frequency.value=440*2**((n.pitch-69)/12);o.connect(gain);o.start(time);o.stop(time+duration+.045);}
async function midiStart(b){stop();ctx ||= new (window.AudioContext||window.webkitAudioContext)();await ctx.resume();const bus=ctx.createGain();bus.connect(ctx.destination);const tr={bus,id:b.id,step:0,next:ctx.currentTime+.06,queue:[],timer:null,raf:null};transport=tr;function schedule(){if(transport!==tr)return;while(tr.next<ctx.currentTime+.10){const n=tr.step,seconds=60/b.bpm/4;for(const note of b.notes)if(note.start===n)midiSound(note,tr.next,note.duration*seconds,bus);tr.queue.push({n,time:tr.next});tr.next+=seconds;tr.step=(n+1)%(b.bars*16);}}function draw(){if(transport!==tr)return;let n;while(tr.queue.length&&tr.queue[0].time<=ctx.currentTime)n=tr.queue.shift().n;if(n!==undefined)document.querySelectorAll('[data-rhythm]').forEach(e=>e.classList.toggle('playing',e.dataset.rhythm===b.id&&Number(e.dataset.step)===n));tr.raf=requestAnimationFrame(draw);}schedule();tr.timer=setInterval(schedule,25);draw();}
function midiBytes(b){midiValidate(b);const ticks=120,tempo=Math.round(60000000/b.bpm),end=b.bars*16*ticks;const events=[{t:0,order:0,bytes:[0xff,0x51,3,(tempo>>16)&255,(tempo>>8)&255,tempo&255]},{t:0,order:0,bytes:[0xff,0x58,4,4,2,24,8]},{t:0,order:0,bytes:[0xc0,0]}];for(const n of b.notes){events.push({t:n.start*ticks,order:2,bytes:[0x90,n.pitch,n.velocity]},{t:(n.start+n.duration)*ticks,order:1,bytes:[0x80,n.pitch,0]});}events.sort((a,c)=>a.t-c.t||a.order-c.order);function vlq(n){const out=[n&127];while(n>>=7)out.unshift((n&127)|128);return out;}const track=[];let previous=0;for(const e of events){track.push(...vlq(e.t-previous),...e.bytes);previous=e.t;}track.push(...vlq(end-previous),0xff,0x2f,0);const size=track.length;return new Uint8Array([77,84,104,100,0,0,0,6,0,0,0,1,1,224,77,84,114,107,(size>>>24)&255,(size>>>16)&255,(size>>>8)&255,size&255,...track]);}
function midiDownload(b){const url=URL.createObjectURL(new Blob([midiBytes(b)],{type:'audio/midi'}));const a=el('a',{href:url,download:(b.name.replace(/[\\/:*?"<>|]/g,'_')||'pattern')+'.mid'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('已导出 MIDI · 可以导入 Cubase 或 Logic。');}

function midiEditNote(b,n){
 stop();const dialog=el('dialog',{});dialog.append(el('h2',{text:'修改 '+midiPitch(n.pitch)}));
 const fields={};for(const [key,label,min,max] of [['pitch','音高 MIDI 编号（60 = C4）',36,96],['start','起点（从第 0 格计）',0,b.bars*16-1],['duration','时值（格）',1,b.bars*16],['velocity','力度',1,127]]){fields[key]=el('input',{type:'number',min,max,value:n[key],'aria-label':label});dialog.append(el('label',{text:label},[fields[key]]));}
 const message=el('p',{class:'muted'});dialog.append(message,el('div',{class:'actions'},[el('button',{text:'取消',onclick:()=>dialog.close()}),el('button',{text:'应用修改',class:'primary',onclick:()=>{const updated={};for(const key of Object.keys(fields))updated[key]=Number(fields[key].value);const copy=clone(b);copy.notes[b.notes.indexOf(n)]=updated;try{midiValidate(copy);}catch(e){message.textContent=e.message;return;}Object.assign(n,updated);changed();dialog.close();render();}})]));dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();
}
