const {webcrypto}=require('node:crypto');
const {File}=require('node:buffer');
class Node {
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.nodeType=1;this.children=[];this.childNodes=this.children;this.attributes={};this.listeners={};this.dataset={};this.value='';this.style={setProperty(){},getPropertyValue(){return ''},[Symbol.iterator]:function*(){}};this.parentNode=null;this.hidden=false;this.open=false;this.checked=false;this.disabled=false;this._text='';this.clientWidth=650;this.clientHeight=460;this.classList={add:(...names)=>{const set=new Set(this.className.split(' ').filter(Boolean));names.forEach(n=>set.add(n));this.className=[...set].join(' ')},remove:(...names)=>{this.className=this.className.split(' ').filter(n=>!names.includes(n)).join(' ')},contains:n=>this.className.split(' ').includes(n),toggle:(n,v)=>{v=v===undefined?!this.classList.contains(n):v;v?this.classList.add(n):this.classList.remove(n);return v}};if(tag==='template')this.content=new Node('fragment');}
 get className(){return this.attributes.class||''}set className(v){this.attributes.class=v}
 set textContent(v){this._text=String(v??'');this.children=[];this.childNodes=this.children;}get textContent(){return this._text+this.children.map(c=>c.textContent||'').join('')}
 set innerHTML(v){this._text=v;this.children=[];this.childNodes=this.children;}get innerHTML(){return this._text}
 get firstChild(){return this.children[0]||{textContent:''}}get parentElement(){return this.parentNode}get firstElementChild(){return this.children[0]}get lastElementChild(){return this.children.at(-1)}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=String(v);if(k==='value')this.value=String(v);if(k==='hidden')this.hidden=true;if(k==='open')this.open=true;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=String(v)}
 getAttribute(k){return this.attributes[k]??null}removeAttribute(k){delete this.attributes[k]}
 append(...cs){cs.forEach(c=>{if(typeof c==='string')c=new Text(c);c.remove?.();c.parentNode=this;this.children.push(c);if(this.tagName==='SELECT'&&(c.selected||!this.value))this.value=c.value;})}appendChild(c){this.append(c);return c}prepend(...cs){cs.reverse().forEach(c=>{c.remove?.();c.parentNode=this;this.children.unshift(c)})}replaceChildren(...cs){this.children.forEach(c=>c.parentNode=null);this.children=[];this.childNodes=this.children;this._text='';this.append(...cs)}insertBefore(c,b){c.parentNode=this;const i=this.children.indexOf(b);this.children.splice(i<0?this.children.length:i,0,c)}remove(){if(this.parentNode){const p=this.parentNode;const i=p.children.indexOf(this);if(i>=0)p.children.splice(i,1);this.parentNode=null}}replaceWith(...cs){const p=this.parentNode;if(!p)return;const i=p.children.indexOf(this);p.children.splice(i,1,...cs);cs.forEach(c=>c.parentNode=p)}
 addEventListener(t,f){(this.listeners[t]||=[]).push(f)}removeEventListener(){}dispatchEvent(e){e.target ||= this;e.currentTarget=this;e.preventDefault ||= ()=>{};e.stopPropagation ||= ()=>{};for(const f of this.listeners[e.type]||[])f(e);if(this['on'+e.type])this['on'+e.type](e);return true}click(){if(!this.disabled)this.dispatchEvent({type:'click'})}focus(){}blur(){this.dispatchEvent({type:'blur'})}showModal(){this.open=true}close(){this.open=false;this.dispatchEvent({type:'close'})}scrollIntoView(){}getBoundingClientRect(){return {width:this.clientWidth,height:this.clientHeight,left:0,top:0,right:this.clientWidth,bottom:this.clientHeight}}contains(n){return n===this||this.children.some(c=>c.contains?.(n))}
 matches(s){return s.split(',').some(sel=>{sel=sel.trim();if(sel.endsWith(':checked'))return this.checked&&this.matches(sel.slice(0,-8));const attr=sel.match(/\[([^=\]]+)(?:=["']?([^"'\]]+)["']?)?\]/);if(attr){if(attr[2]!==undefined&&this.getAttribute(attr[1])!==attr[2])return false;if(attr[2]===undefined&&this.getAttribute(attr[1])===null)return false;sel=sel.replace(attr[0],'')}const id=sel.match(/#([\w-]+)/);if(id&&this.id!==id[1])return false;const classes=[...sel.matchAll(/\.([\w-]+)/g)].map(x=>x[1]);if(classes.some(c=>!this.classList.contains(c)))return false;const tag=sel.match(/^[\w-]+/);return !tag||this.tagName===tag[0].toUpperCase()})}
 querySelectorAll(s){const parts=s.trim().split(/\s+/);let out=[];function walk(n){for(const c of n.children||[]){if(c.nodeType===1){if(c.matches(parts.at(-1))){let parent=c.parentNode,ok=true;for(let i=parts.length-2;i>=0;i--){while(parent&&!parent.matches(parts[i]))parent=parent.parentNode;if(!parent){ok=false;break}parent=parent.parentNode}if(ok)out.push(c)}walk(c)}}}walk(this);return out}
 querySelector(s){return this.querySelectorAll(s)[0]||null}closest(s){let n=this;while(n){if(n.matches?.(s))return n;n=n.parentNode}return null}
 getContext(){return {setTransform(){},clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},setLineDash(){},arc(){},fill(){},fillRect(){},fillText(){},measureText(t){return {width:t.length*12}},createLinearGradient(){return {addColorStop(){}}}}}pause(){}play(){return Promise.resolve()}setPointerCapture(){}
}
class Text {constructor(s){this.nodeType=3;this.textContent=s}remove(){}}
class Doc extends Node {constructor(){super('document');this.body=new Node('body');this.append(this.body)}createElement(t){return new Node(t)}createElementNS(ns,t){return new Node(t)}createTextNode(s){return new Text(s)}getElementById(id){return this.querySelector('#'+id)}getSelection(){return {rangeCount:0}}}
function setup(){const document=new Doc();const aside=new Node('aside'),main=new Node('main'),header=new Node('header'),actions=new Node('div');actions.className='actions';header.append(actions);main.append(header);document.body.append(aside,main);const brand=new Node('a');brand.className='brand';aside.append(brand);for(const id of ['search','nav','newPage']){const n=new Node(id==='search'?'input':id==='nav'?'nav':'button');n.id=id;aside.append(n)}for(const id of ['crumb','edit','save','cloud']){const n=new Node(id==='crumb'?'span':'button');n.id=id;actions.append(n)}for(const id of ['title','meta','add','blocks','status','export','import','importFile','deletePage']){const n=new Node(id==='importFile'?'input':'div');n.id=id;main.append(n)}const sync=new Node('dialog');sync.id='sync';const desc=new Node('p');sync.append(desc);for(const id of ['owner','repo','branch','token']){const label=new Node('label');label.append(new Text('label'));const n=new Node('input');n.id=id;n.value=id==='branch'?'main':'';label.append(n);sync.append(label)}const hint=new Node('p');hint.className='muted';hint.append(new Text('hint'));sync.append(hint);const stat=new Node('p');stat.id='syncStatus';sync.append(stat);const buttons=new Node('div');buttons.className='actions';for(const id of ['closeSync','pull','push']){const n=new Node('button');n.id=id;buttons.append(n)}sync.append(buttons);document.body.append(sync);
 const stored=new Map(),sessions=new Map(),assets=new Map();const storage=map=>({getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)});
 const db={createObjectStore(){},transaction(){const tx={objectStore(){return {get(id){const r={};queueMicrotask(()=>{r.result=assets.get(id);r.onsuccess?.()});return r},put(value,id){assets.set(id,value);queueMicrotask(()=>tx.oncomplete?.())}}}};return tx}};
 const window={devicePixelRatio:1,innerWidth:1200,innerHeight:900,addEventListener(){},getSelection(){return {rangeCount:0}},AudioContext:null};return {document,window,Node,assets,stored,sessions,crypto:webcrypto,File,Blob,URL,TextEncoder,TextDecoder,localStorage:storage(stored),sessionStorage:storage(sessions),indexedDB:{open(){const r={};queueMicrotask(()=>{r.result=db;r.onupgradeneeded?.();r.onsuccess?.()});return r}},MutationObserver:class{observe(){}},ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}disconnect(){}},requestAnimationFrame:()=>0,cancelAnimationFrame(){},setTimeout,clearTimeout,setInterval:()=>0,clearInterval(){},Date,Math,Set,Map,console,location:{pathname:'/music-notebook/'},fetch:async()=>({ok:false,status:404,json:async()=>({})}),confirm:()=>true,prompt:()=>null,atob:s=>Buffer.from(s,'base64').toString('binary'),btoa:s=>Buffer.from(s,'binary').toString('base64'),FileReader:class{readAsDataURL(blob){blob.arrayBuffer().then(buf=>{this.result='data:'+(blob.type||'application/octet-stream')+';base64,'+Buffer.from(buf).toString('base64');this.onload?.()})}}};}
module.exports={setup,Node};
