const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const {setup}=require('./fake-dom.cjs');const env=setup(),context=vm.createContext(env);const run=s=>vm.runInContext(s,context);const files=['midi','app','modules','drums','whiteboard','workbench','archive-core','archive-practice','archive-graph','archive-journal','archive-sync'];for(const f of files){try{run(fs.readFileSync(require('node:path').join(__dirname,'..',f+'.js'),'utf8'))}catch(e){console.error('LOAD',f);throw e}}
(async()=>{await new Promise(r=>setTimeout(r,1));run('data=validate(clone(defaults));current=data.pages[0].id;render();');console.log('PASS startup and home render');
const state=()=>JSON.parse(run('JSON.stringify(data)'));let d=state();assert.equal(d.pages.length,2);assert.equal(d.instruments.length,2);assert.equal(d.pages[0].blocks[0].children[0].id,'intro');const serialized=run('JSON.stringify(data)');run('archiveMigrate(data)');assert.equal(run('JSON.stringify(data)'),serialized);console.log('PASS legacy IDs, content and idempotent migration');
run('Archive.view="directory";render();Archive.view="practice";render();Archive.view="instrument";render();Archive.view="works";render();');console.log('PASS all module renders');
run('const testCourse=archiveCreate("course","测试课程",{});const testChapter=archiveCreate("chapter","第一章",{courseId:testCourse.id});const testPage=archiveCreate("lesson","拍号",{courseId:testCourse.id,chapterId:testChapter.id});const testPoint=archiveCreate("point","四四拍",{courseId:testCourse.id,chapterId:testChapter.id,pageId:testPage.id});testPoint.needsPractice=true;testPoint.practiceAddedAt=new Date().toISOString();Archive.view="knowledge";render();');assert.equal(run('testPoint.type'),'group');console.log('PASS four-level creation and knowledge editor');
run('const plan={id:uid(),date:archiveDate(),title:"测试",items:[{id:uid(),nodeId:testPoint.id,done:false}]};data.dailyPlans.push(plan);archiveRecordSession(testPoint.id,120,"again",{planId:plan.id,itemId:plan.items[0].id});');assert.equal(run('plan.items[0].done'),true);assert.equal(run('testPoint.needsPractice'),true);assert.equal(run('archiveSessionStats(testPoint.id).count'),1);run('archiveRecordSession(testPoint.id,180,"stuck",null)');assert.equal(run('archiveSessionStats(testPoint.id).seconds'),300);assert.equal(run('testPoint.proficiency'),'stuck');console.log('PASS repeat duration/count, completed daily task stays complete');
run('archiveFeedbackDialog(testPoint.id,60,null,true);document.querySelectorAll("dialog").at(-1).close();');assert.equal(run('testPoint.proficiency'),'again');assert.equal(run('archiveSessionStats(testPoint.id).count'),3);console.log('PASS skipped feedback defaults to again exactly once');
run('testPoint.proficiency="fluent";data.practiceSessions.at(-1).feedback="fluent"');assert.equal(run('archiveRecommendation(archiveEntries(),"balanced").length'),0);run('testPoint.proficiency="stuck";data.practiceSessions.at(-1).feedback="stuck";Archive.view="practice";Archive.practiceTab="graph";render();');assert.ok(run('document.getElementById("blocks").querySelector("canvas")'));console.log('PASS proficiency recommendation and 3D graph render');
run('Archive.practiceTab="organize";render();archivePlanDialog();archiveListDialog();archiveListDetail({id:"demo",name:"组合",items:[testPoint.id]});');console.log('PASS classification, planning and list dialogs');
run('Archive.view="instrument";render();archiveInstrumentItemDialog(data.instruments[0]);archiveInstrumentSchedule(data.instruments[0]);archiveInstrumentRecordDialog(data.instruments[0]);');console.log('PASS instrument item/schedule/record dialogs');
run('const testWork={id:uid(),title:"作品测试",types:["编曲"],stages:[{id:uid(),title:"草稿",date:archiveDate(),note:"修改",files:[]}]};data.works.push(testWork);Archive.work=testWork.id;Archive.view="works";render();archiveWorkDialog(testWork);archiveStageDialog(testWork);');assert.equal(run('validate(clone(data)).works.length'),1);console.log('PASS work stages and validation');
run('archiveDelete("point",testPoint.id);');const dialogs=run('document.querySelectorAll("dialog")');const latest=dialogs.at(-1);latest.querySelectorAll('button').find(b=>b.textContent==='确认').click();assert.equal(run('!!archiveFind(testPoint.id)'),false);env.document.getElementById('archive-undo').querySelector('button').click();assert.equal(run('!!archiveFind(testPoint.id)'),true);console.log('PASS cascading deletion and undo');
run('data=validate({version:1,pages:[],courses:[],archiveInitialized:true});Archive.view="home";render();');assert.equal(run('data.pages.length'),0);console.log('PASS delete all pages without crash');
run('data=validate(clone(defaults));current=data.pages[0].id;Archive.view="home";render();');
let rejected=false;try{run('validate({version:1,pages:[],courses:[{id:"x",title:"bad",chapters:1}]})')}catch{rejected=true}assert.equal(rejected,true);console.log('PASS malformed import rejected');
// Exercise real dialog handlers for a custom list, plan generation and instrument feedback.
run('data.pages[0].blocks[0].needsPractice=true;archivePickList(data.pages[0].blocks[0].id);');
let dialog=env.document.querySelectorAll('dialog').at(-1);dialog.querySelectorAll('button').find(b=>b.textContent==='＋ 新建练习单').click();dialog=env.document.querySelectorAll('dialog').at(-1);dialog.querySelector('input').value='自建测试单';dialog.querySelectorAll('button').find(b=>b.textContent==='创建').click();assert.equal(run('data.practiceLists.length'),1);assert.equal(run('data.practiceLists[0].items.length'),1);console.log('PASS create a list from a knowledge node');
run('archivePlanDialog(data.practiceLists[0])');dialog=env.document.querySelectorAll('dialog').at(-1);dialog.querySelectorAll('button').find(b=>b.textContent==='查看候选内容 →').click();dialog.querySelectorAll('button').find(b=>b.textContent==='生成今日计划').click();assert.equal(run('data.dailyPlans.at(-1).items[0].nodeId'),run('data.practiceLists[0].items[0]'));console.log('PASS playlist plan preserves selection and order');
run('const gi=data.instruments[0];gi.items.push({id:"guitar-item",title:"推弦",state:"again"});archiveInstrumentStart(gi,gi.items[0]);');assert.equal(run('Archive.timer.instrumentId'),run('data.instruments[0].id'));run('document.getElementById("archive-timer").querySelectorAll("button").find(b=>b.textContent==="结束练习").click()');dialog=env.document.querySelectorAll('dialog').at(-1);const fileInput=dialog.querySelectorAll('input').find(n=>n.getAttribute('type')==='file');fileInput.files=[];dialog.querySelectorAll('button').find(b=>b.textContent==='完成').click();await new Promise(r=>setTimeout(r,5));assert.equal(run('data.instruments[0].sessions.length'),1);assert.equal(run('data.instruments[0].sessions[0].feedback'),'again');assert.equal(run('Archive.timer'),null);console.log('PASS instrument timer saves default feedback');
run('Archive.view="practice";Archive.practiceTab="graph";render();const gp1=JSON.stringify(archiveGraphPositions(archiveEntries(),archiveGraphModel().edges));data.pages[0].blocks[0].practiceTags=["分类"];const gp2=JSON.stringify(archiveGraphPositions(archiveEntries(),archiveGraphModel().edges));');assert.equal(run('gp1'),run('gp2'));console.log('PASS classifying nodes leaves graph positions unchanged');
// Verify an atomic content+attachment submission through a mocked GitHub API.
run('const mediaFile=new File(["test"],"audio.wav",{type:"audio/wav"});');env.assets.set('asset-test',run('mediaFile'));run('data.works.push({id:"w",title:"同步",types:["演唱"],stages:[{id:"s",title:"阶段",date:archiveDate(),files:[{id:"asset-test",assetId:"asset-test",src:"asset:asset-test",name:"audio.wav",type:"audio/wav"}]}]});archiveConnected=true;archiveToken="TEST_TOKEN";settings={owner:"test",repo:"repo",branch:"main"};bases[key(settings)]=null;');const calls=[];env.fetch=async(url,options={})=>{calls.push({url,method:options.method||'GET',payload:options.body?JSON.parse(options.body):null});const path=url.split('/repos/test/repo')[1];const ok=x=>({ok:true,status:200,json:async()=>x});if(path.startsWith('/contents/content.json'))return {ok:false,status:404,json:async()=>({})};if(path==='/git/ref/heads/main')return ok({object:{sha:'parent'}});if(path==='/git/commits/parent')return ok({tree:{sha:'base-tree'}});if(path==='/git/blobs')return ok({sha:options.body.includes('utf-8')?'content-sha':'asset-sha'});if(path==='/git/trees')return ok({sha:'new-tree'});if(path==='/git/commits')return ok({sha:'new-commit'});if(path==='/git/refs/heads/main')return ok({object:{sha:'new-commit'}});throw Error('unexpected '+path)};context.fetch=env.fetch;await run('archiveSaveGitHub()');const tree=calls.find(c=>c.url.endsWith('/git/trees')).payload;assert.equal(tree.tree.length,2);assert.equal(tree.tree.find(i=>i.path==='content.json').sha,'content-sha');assert.equal(calls.at(-1).payload.force,false);assert.equal(run('dirty'),false);assert.equal(run('data.works.at(-1).stages[0].files[0].src'),'./assets/asset-test.wav');assert.ok(!run('JSON.stringify(data)').includes('TEST_TOKEN'));console.log('PASS atomic GitHub upload, media refs and token exclusion');
// A remote content change must prevent write operations.
calls.length=0;context.fetch=async(url,options={})=>{calls.push({url,method:options.method||'GET'});if(url.includes('/contents/'))return {ok:true,json:async()=>({sha:'other-device',content:Buffer.from(run('JSON.stringify(data)')).toString('base64')})};return {ok:true,json:async()=>({object:{sha:'parent'}})}};await run('archiveSaveGitHub()');assert.equal(calls.filter(c=>c.method!=='GET').length,0);console.log('PASS remote conflict refuses writes');
console.log('ALL INTEGRATION CHECKS PASSED');})().catch(e=>{console.error(e);process.exitCode=1});
